### ISSUE TITLE
Notifications to Twitch Chat

### ISSUE THREAD

**Issue by SantiMA10** [streamdevs/webhook#12]
It could be nice if we send the notifications to the Twitch Chat too.

StreamLabs API doesn't have support for custom bot commands, we should use the [Twitch API](https://dev.twitch.tv/docs/irc) directly.

## Implementation plan
- [x] Create new TwitchChat service #34 
- [x] Create new StreamLabsAlert service #40 
- [x] Load TwitchChat configuration from the environment #43 
- [x] Use StraemLabs service instead of axios #44
- [ ] Use the TwitchChat service to send messages to the chat with the GitHub events 
    - [x] Star events #49
    - [x] Pull Request events #64 
    - [x] Ping events #65
    - [x] Fork events #72 @orestes

**Comment by SantiMA10** [comment]
@orestes should we send a message to the Twitch with the `ping` event?

**Comment by SantiMA10** [comment]
🎉
