### ISSUE TITLE
Add GitLab support for MR merged events

### ISSUE THREAD

**Issue by SantiMA10** [streamdevs/webhook#152]
docs: https://docs.gitlab.com/ee/user/project/integrations/webhooks.html

# Implementation plan
- [x] new `/gitlab` endpoint #153 
- [x] new `MergeRequestMerged` reaction for GitLab #156 
- [ ] add `MergeRequestMerged` reaction to `/gitlab` endpoint #160
~new "`Ping`" reaction for GitLab~
