### ISSUE TITLE
Parse pull request events

### ISSUE THREAD

**Issue by SantiMA10** [streamdevs/webhook#26]
The idea is to allow also [`Pull Request` events](https://developer.github.com/v3/activity/events/types/#pullrequestevent) to be sent as a notification to the streaming.

I think we only want the "happy" events, so... we only need to parse the `opened` and `closed` with `merged` set to `true`.

# Implementation plan
- [x] Move the route definition to their own file. #28 
- [x] Move the joi validation to their own file. #29 
- [x] Add new logic to handle the `Pull Request` `opened` event. #30
- [x] Add new logic to handle the `Pull Request` `closed` and `merged` event. #31

**Comment by orestes** [comment]
Pending resolving conflicts on #31

**Comment by orestes** [comment]
Now that #31 is merged, this issue can be closed :)
