### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by SantiMA10** [streamdevs/webhook#50]
We want to add TypeScript to the project in order to have type checking!

# Implementation plan
- [x] Add `tsc` to the project with `allowJs: true` #70 @SantiMA10 
- [x] Add a build step to our pipeline, in order to check if our app compiles #71 @SantiMA10 
- [x] Add a build step to `app.json`, `heroku` doesn't understand `TypeScript` 😉 #82 @orestes 
- [x] Add support for `TypeScript` in `jest` by using `ts-jest` #85 @SantiMA10 
- [x] Migrate our test suite to `TypeScript` @SantiMA10 
   - [x] #92 
   - [x] #93 
   - [x] #94 
   - [x] #95 
   - [x] #96 
   - [x] #97 
   - [x] #98  
- [x] Migrate .js files to .ts files adding types
   - [x] #99 
   - [x] #100
   - [x] #101
   - [x] #102
   - [x] Migrate `ping` event @SantiMA10 #104
   - [x] Migrate `star` event @SantiMA10 #110
   - [x] Migrate `pull_request` event
       - [x] `Pull Request Opened` @SantiMA10 #113 
       - [x] `Pull Request Merged` @SantiMA10 #115
   - [x] Migrate `fork` event @orestes #117 
   - [x] Migrate `route/index.js` @SantiMA10 #118
   - [x] Migrate `index.js` @SantiMA10 #119 
- [x] Remove `allowJs: true` from `tsconfig.json` @orestes #122 
- [x] Add support for `TypeScript` in our `eslint` configuration #124
- [ ] Create types for the Payloads @SantiMA10 

<details>
  <summary>Meme!</summary>
![image](https://user-images.githubusercontent.com/7255298/79270960-52aa1700-7e9f-11ea-929c-5bbb0b9551a7.png)
</details>

**Comment by SantiMA10** [comment]
@orestes feedback welcome!
