### ISSUE TITLE
Handle check runs

### ISSUE THREAD

**Issue by orestes** [streamdevs/webhook#56]
Check Run events happen when the CI server (GitHub Actions) run.
We want these notifications to be handled and shown on the stream when

- The build is successful for specific branches
- The build fails for specific branches

# Implementation plan

- [x] Add implementation
- [x] Add unit tests 
- [x] Include in `reactionBuild`
- [x] Add `check_run` events to the events expected in `ping`
- [x] Add integration tests
- [x] Notify only for branches  in a list `NOTIFY_CHECK_RUNS_FOR` or all of them if the list is empty #141
- [x] Document parameter in readme
- [x] Add new configuration variable in `app.json`

**Comment by SantiMA10** [comment]
Maybe if we only send the fail/error event

**Comment by orestes** [comment]
Implemented in  #136
