### ISSUE TITLE
Handle issues

### ISSUE THREAD

**Issue by orestes** [streamdevs/webhook#58]
# Implementation plan
- [x] Issue opened #129 
- [x] Assigned issues @SantiMA10 #132 
- [x] Add issue opened reaction to reactionBuild method #133
- [x] Add `issues` to ping event #134

**Comment by SantiMA10** [comment]
docs: https://developer.github.com/v3/activity/events/types/#issuesevent

**Comment by SantiMA10** [comment]
@orestes do you think other issue events like `assigned` are interesting?
