### ISSUE TITLE
Handle release events

### ISSUE THREAD

**Issue by orestes** [streamdevs/webhook#61]
Docs https://developer.github.com/v3/activity/events/types/#releaseevent

# Implementation plan

- [x] Allow `release` events on webhook `ping`
- [x] Add `ReleaseCreated` to the `reactionBuild` function
- [x] Handle `release` events, only when they're published
- [x] Unit-test the reaction
- [x] Test the reaction with integration tests
